# Generated by Django 5.2.3 on 2025-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['title'], 'verbose_name': 'Netflix Title', 'verbose_name_plural': 'Netflix Titles'},
        ),
        migrations.AlterField(
            model_name='title',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='listed_in',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='show_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
